### ISSUE TITLE
Question: Mask approach to random string

### ISSUE THREAD

**Issue by k-funk** [crouchcd/pkce-challenge#4]
Out of curiosity, was there a reason to generate the random string using the mask of characters?

`crypto` provides a `randomBytes` function: `crypto.randomBytes(32)` as mentioned in https://auth0.com/docs/flows/call-your-api-using-the-authorization-code-flow-with-pkce#create-code-verifier, just wondering if there was a technical reason for doing it the way you did.

**Comment by crouchcd** [comment]
The mask is already URL safe, so no need to base64URLEncode it.

```js
base64URLEncode(crypto.randomBytes(32));
```

^as a verifier will give a URL safe string omitting the chars `.` and `~`. 

I know the mask provides 66 characters to choose from at random whereas a random byte provides 256, but I'm not sure if the randomBytes approach provides more randomness since it has to be converted to base64.

**Comment by k-funk** [comment]
Interesting! I made a codesandbox to compare the two, in case anyone else in interested: https://codesandbox.io/s/pkce-challenge-vs-cryptorandombytes-f9yz2?file=/src/index.js

You can see that the verifiers from this library have the `.` and `~` characters, as @crouchcd suggested, but the encoded `crypto.randomBytes` do not.
